version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pms_postgres_dev
    environment:
      POSTGRES_DB: pms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - pms_dev_network

  redis:
    image: redis:7-alpine
    container_name: pms_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - pms_dev_network

  backend:
    build:
      context: ./pms-backend
      dockerfile: Dockerfile
    container_name: pms_backend_dev
    environment:
      - DATABASE_URL=postgresql+asyncpg://pms_admin:PmsAdmin@10.10.150.85:6297/pms
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - REQUIRE_AUTH=false
    ports:
      - "8000:8000"
    volumes:
      - ./pms-backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - pms_dev_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  pms_dev_network:
    driver: bridge